### ISSUE TITLE
Incorrect address for osu filename

### ISSUE THREAD

**Issue by yaggod** [Piotrekol/ProcessMemoryDataFinder#22]
Seems like even after updating addresses, GetOsuFileName() is returning wrong value, so it doesn't work with osu!trainer
![image](https://github.com/Piotrekol/ProcessMemoryDataFinder/assets/71946695/eff3c7f7-8f71-4507-8043-9970a9921389)

![image](https://github.com/Piotrekol/ProcessMemoryDataFinder/assets/71946695/4d16fa6f-7f43-4a26-985a-ee770923158b)

**Comment by Piotrekol** [comment]
should be available as 0.10.2 on nuget shortly.
